<a href="https://colab.research.google.com/github/RajivDalal/ML_practice/blob/main/Numpy_(Day_4).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy
- Used for numerical operations
- Provides multidimensional arrays

In [ ]:
import numpy as np

# Arrays
- Have a single data type
- Converts the rest of data to highest data type
- Bool -> Int -> Float -> String
- Faster than Python lists

In [ ]:
var = np.array([1,2,3,4])
print(type(var))

<class 'numpy.ndarray'>


In [ ]:
arr = np.array([1.,True])
print(arr)

[1. 1.]


In [ ]:
a = np.array([1,2,3,4,5])
print(a)
print(a.ndim)
print(a.dtype) #Returns the data type of array

[1 2 3 4 5]
1
int64


In [ ]:
b = np.array([[1,2,3,4],[5,6,7,8]])
print(b)
print(b.ndim)

[[1 2 3 4]
 [5 6 7 8]]
2


# Numpy Functions
- zeros: Creates an array of zeroes
- ones: Creates an array of ones

- argmax: Index position with max value
- argmin: Index position with max value
- argsort: Sorts based on index position

- arange: Makes a

In [ ]:
c = np.zeros(10)
print(d)
d = np.ones(5)
print(e)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


In [ ]:
e = np.zeros((3,4,5))
print(e)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [ ]:
f = np.ones((3,3,4,5))
print(f)

[[[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]


 [[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]


 [[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]]


In [ ]:
var = np.array([10,40,25,20])
print(var.size)

4


In [ ]:
print(var.argmax())
print(var.argmin())
print(var.argsort())

1
0
[0 3 2 1]


In [ ]:
#Indexing and slicing
print(var[0])
print(var[1:3])

10
[40 25]


In [ ]:
print(np.arange(15)) #end(excluded)
print(np.arange(3,7)) #start,end(excluded)
print(np.arange(0,100,10)) #start,end(excluded),step

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[3 4 5 6]
[ 0 10 20 30 40 50 60 70 80 90]


In [ ]:
a = np.arange(12)
print(a.reshape(4,3))
print("\n")
print(a.reshape(2,2,3))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [ ]:
x = [1,4,9,16,25]
print(np.sqrt(x))
print(np.log(x))
print(np.exp(x))
print(np.mean(x))

[1. 2. 3. 4. 5.]
[0.         1.38629436 2.19722458 2.77258872 3.21887582]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10]


In [ ]:
a1 = a.reshape(3,4)
print(a1.T)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [ ]:
arr = np.array([10.8,3.50,7.4])
print(arr)
print(np.floor(arr))
print(np.ceil(arr))
print(np.round(arr))

[10.8  3.5  7.4]
[10.  3.  7.]
[11.  4.  8.]
[11.  4.  7.]


# Stacking
- Joining
- Two types  
  - Vertical Stacking: No. of rows should be same
  - Horizontal Stacking No. of columns should be same

In [ ]:
arr1 = np.arange(10).reshape(2,5)
arr2 = np.arange(20).reshape(4,5)
print(arr1,arr2,sep="\n\n",end="\n")

arr3 = np.arange(10).reshape(5,2)
arr4 = np.arange(20).reshape(5,4)
print(arr3,arr4,sep="\n\n")

[[0 1 2 3 4]
 [5 6 7 8 9]]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [ ]:
#Vertical stacking
np.vstack((arr1,arr2))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
#Horizontal stacking
np.hstack((arr3,arr4))

array([[ 0,  1,  0,  1,  2,  3],
       [ 2,  3,  4,  5,  6,  7],
       [ 4,  5,  8,  9, 10, 11],
       [ 6,  7, 12, 13, 14, 15],
       [ 8,  9, 16, 17, 18, 19]])

# Splitting
- Two types  
  - Vertical Splitting
  - Horizontal Splitting

In [ ]:
arr5 = np.arange(100).reshape(10,10)
print(np.vsplit(arr5,2))
print(np.hsplit(arr5,2))

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]]), array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])]
[array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44],
       [50, 51, 52, 53, 54],
       [60, 61, 62, 63, 64],
       [70, 71, 72, 73, 74],
       [80, 81, 82, 83, 84],
       [90, 91, 92, 93, 94]]), array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29],
       [35, 36, 37, 38, 39],
       [45, 46, 47, 48, 49],
       [55, 56, 57, 58, 59],
       [65, 66, 67, 68, 69],
       [7

In [ ]:
#Linspace
np.linspace(0,30,100)

array([ 0.        ,  0.3030303 ,  0.60606061,  0.90909091,  1.21212121,
        1.51515152,  1.81818182,  2.12121212,  2.42424242,  2.72727273,
        3.03030303,  3.33333333,  3.63636364,  3.93939394,  4.24242424,
        4.54545455,  4.84848485,  5.15151515,  5.45454545,  5.75757576,
        6.06060606,  6.36363636,  6.66666667,  6.96969697,  7.27272727,
        7.57575758,  7.87878788,  8.18181818,  8.48484848,  8.78787879,
        9.09090909,  9.39393939,  9.6969697 , 10.        , 10.3030303 ,
       10.60606061, 10.90909091, 11.21212121, 11.51515152, 11.81818182,
       12.12121212, 12.42424242, 12.72727273, 13.03030303, 13.33333333,
       13.63636364, 13.93939394, 14.24242424, 14.54545455, 14.84848485,
       15.15151515, 15.45454545, 15.75757576, 16.06060606, 16.36363636,
       16.66666667, 16.96969697, 17.27272727, 17.57575758, 17.87878788,
       18.18181818, 18.48484848, 18.78787879, 19.09090909, 19.39393939,
       19.6969697 , 20.        , 20.3030303 , 20.60606061, 20.90

# Random Functions

In [ ]:
print(np.random.random(10)) #Random Array (rand function is same)
print(np.random.randint(1,10)) #Random integer


[0.5538212  0.76348293 0.75037092 0.85799397 0.33347628 0.69869741
 0.18926434 0.65467354 0.35853354 0.00779086]
9
